services:
  redis:
    image: redis:7.4-alpine
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data
    healthcheck:
      test:
        - CMD-SHELL
        - 'redis-cli -h localhost -p 6379 ping'
      interval: 20s
      timeout: 20s
      retries: 10


volumes:
  redis_data:
    driver: local

