# Generated by Django 6.0.6 on 2026-06-08 15:03

import blog.utils
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.utils.get_image_upload_path, verbose_name='Foto'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(default=blog.utils.generate_cuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('image_cover', models.ImageField(blank=True, null=True, upload_to=blog.utils.get_cover_upload_path, verbose_name='Capa')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='draft', max_length=10, verbose_name='Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
