# Generated by Django 6.0.6 on 2026-09-04 15:51

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_tag_post_category_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default=blog.utils.get_image_default_path, null=True, upload_to=blog.utils.get_image_upload_path, verbose_name='Foto'),
        ),
    ]
